Настроенные модели
whodef/api_yamdb pull request #4
Opened 2022-07-19 10:13 UTC by on1y4fun

Требуется ревью

2022-07-19 11:01 UTC, whodef commented
Approved

2022-07-19 15:25 UTC, Svolkov-nsk commented
Макс, замечаний у меня несколько:
1. Строка 28:  "on_delete=models.DO_NOTHING" - мне кажется, судя по ТЗ, нужно использовать on_delete=models.SET_NULL. (https://www.delftstack.com/ru/howto/django/django-on_delete-parameter/); То же самое строки 36, 37
2. Не везде используешь verbose_name. Давай добавим для каждого поля, а то сильно бросается в глаза.
3.  Не увидел поля рейтинг для модели Title . По ТЗ у произведения должен быть рейтинг от 1 до 10

2022-07-20 15:11 UTC, whodef requested changes
С моделями, всё вроде хорошо! =)

2022-07-20 15:11 UTC, whodef commented on api_yamdb/api/serializers.py
> +        fields = '__all__'
Для безопасности (как говорил мой ревьюер) лучше использовать конкретные поля.
Например:
`fields = ('id', 'author', 'post', 'text', 'created', )`

2022-07-20 15:11 UTC, whodef commented on api_yamdb/api/serializers.py
> +        fields = '__all__'
А для пущей безопасности (но это на твоё усмотрение уже) можно добавить поле:
`read_only_fields = ('id', 'author', 'created', )`

2022-07-20 15:11 UTC, whodef commented on api_yamdb/api/serializers.py
> +        fields = '__all__'
ну и здесь подправить

2022-07-20 16:20 UTC, Svolkov-nsk commented on api_yamdb/api/serializers.py
> +        fields = '__all__'
> Для безопасности (как говорил мой ревьюер) лучше использовать конкретные поля. Например: `fields = ('id', 'author', 'post', 'text', 'created', )`

А мой ревьювер наоборот говорил, что если показываем все поля, то лучше использовать __all__. Думаю, делаем по требованиям ревьювера Тани, т.к. он будет проверять.

2022-07-20 16:20 UTC, Svolkov-nsk commented on api_yamdb/api/serializers.py
> +        fields = '__all__'
поправил у себя, сегодня выкачу на ревью вместе с вьюсетами.

2022-07-20 17:57 UTC, merged